# Generated by Django 3.2 on 2022-05-11 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='steet_address1',
            new_name='street_address1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='steet_address2',
            new_name='street_address2',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='towm_or_city',
            new_name='town_or_city',
        ),
    ]
